const BASE_API_URL = process.env.NEXT_PUBLIC_BASE_API_URL;

// Add these for debugging
const IS_DEVELOPMENT = process.env.NODE_ENV === "development";
const FRONTEND_URL =
  process.env.NEXT_PUBLIC_FRONTEND_URL || "http://localhost:3000";

const NEXT_PUBLIC_GOOGLE_MAPS_API_KEY =
  process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;

const NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME =
  process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME;

const NEXT_PUBLIC_CLOUDINARY_API_KEY =
  process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY;

const NEXT_PUBLIC_CLOUDINARY_API_SECRET =
  process.env.NEXT_PUBLIC_CLOUDINARY_API_SECRET;

export {
  BASE_API_URL,
  IS_DEVELOPMENT,
  FRONTEND_URL,
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
  NEXT_PUBLIC_CLOUDINARY_API_KEY,
  NEXT_PUBLIC_CLOUDINARY_API_SECRET,
};
